development:
  dialect: {{envOr "DB_DIALECT" "postgres"}}
  database: {{envOr "DEV_DB_NAME" "blog_dev"}}
  host: {{envOr "DEV_DB_HOST" "127.0.0.1"}}
  port: {{envOr "DEV_DB_PORT" "5432"}}
  user: {{envOr "DB_USER_ACC" "postgres"}}
  password: {{envOr "DB_USER_PWD" "postgres"}}

test:
  dialect: {{envOr "DB_DIALECT" "postgres"}}
  database: {{envOr "TEST_DB_NAME" "blog_dev"}}
  host: {{envOr "TEST_DB_HOST" "127.0.0.1"}}
  port: {{envOr "TEST_DB_PORT" "5432"}}
  user: {{envOr "DB_TEST_USER_ACC" "onlyfortest"}}
  password: {{envOr "DB_TEST_USER_PWD" "simplepassword"}}

production:
  dialect: {{envOr "DB_DIALECT" "postgres"}}
  database: {{envOr "DB_NAME" "blog"}}
  host: {{envOr "DB_HOST" "127.0.0.1"}}
  port: {{envOr "DEV_DB_PORT" "5432"}}
  user: {{envOr "DB_USER_ACC" "postgres"}}
  password: {{envOr "DB_USER_PWD" "postgres"}}

